name: Update Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update website
        run: |
          # Lógica para actualizar el archivo JSON con los comandos

          # Ejemplo de actualización de un archivo commands.json en la raíz del repositorio
          echo '$commands' > commands.json

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update commands"
          git push
